name: GraalVM Enterprise Edition build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.1.0.1'
          gds-token: ${{ secrets.GDS_TOKEN }}
          java-version: '11'
          components: 'native-image,ruby,python,js,R' 
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Example step
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          gu --version
          native-image --version
          cp /home/runner/work/graalvm_demo/graalvm_demo/1.jit/CountUppercase.java .
          /home/runner/work/graalvm_demo/graalvm_demo/1.jit/demo.sh
          cp /home/runner/work/graalvm_demo/graalvm_demo/2.native/ListDir.java .
          /home/runner/work/graalvm_demo/graalvm_demo/2.native/build.sh
          /home/runner/work/graalvm_demo/graalvm_demo/2.native/demo.sh
          cp /home/runner/work/graalvm_demo/graalvm_demo/3.polyglot/Sample.java .
          /home/runner/work/graalvm_demo/graalvm_demo/3.polyglot/graal.sh
